export const GET_STUDENT_START = "GET_STUDENT_START";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_ERROR = "GET_STUDENT_ERROR";

export const ADD_STUDENT_START = "ADD_STUDENT_START";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";

export const DELETE_STUDENT_START = "DELETE_STUDENT_START";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR";

export const UPDATE_STUDENT_START = "UPDATE_STUDENT_START";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_ERROR = "UPDATE_STUDENT_ERROR";




 

 

